In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
import sys
print(sys.executable)


/home/hp/jupyter/venv/bin/python3


In [3]:
%pip install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 5.7 MB/s  0:00:03m 5.5 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
print(np.__version__)

2.4.6


In [5]:
# From Python Lists
import numpy as np
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
 
# Special Arrays
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)


print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(3,)
1
3
int64


In [3]:
# From Python Lists
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
 
np.ones((2, 4))



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
import numpy as np

# From Python Lists
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:")
print(arr)

print("\n2D Array:")
print(arr_2d)

# Special Arrays
print("\nZeros Array:")
print(np.zeros((3, 3)))

print("\nOnes Array:")
print(np.ones((2, 4)))

print("\nIdentity Matrix:")
print(np.eye(3))

print("\nArange:")
print(np.arange(0, 10, 2))

print("\nLinspace:")
print(np.linspace(0, 1, 5))

print("\nRandom Uniform Numbers:")
print(np.random.rand(3, 2))

print("\nRandom Normal Numbers:")
print(np.random.randn(3, 2))

1D Array:
[1 2 3]

2D Array:
[[1 2 3]
 [4 5 6]]

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Arange:
[0 2 4 6 8]

Linspace:
[0.   0.25 0.5  0.75 1.  ]

Random Uniform Numbers:
[[0.11103537 0.46231362]
 [0.03738858 0.7995579 ]
 [0.08843627 0.13232458]]

Random Normal Numbers:
[[-0.1294849   0.0338089 ]
 [-0.14212182  0.40751514]
 [-0.14698361  1.11641215]]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:")
print(arr)

print("\nShape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Total Elements:", arr.size)
print("Data Type:", arr.dtype)


Array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Dimensions: 2
Total Elements: 6
Data Type: int64


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)
 
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B
 
# Aggregation
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

np.float64(1.118033988749895)

In [7]:
import numpy as np

# Arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)
print("a * b =", a * b)
print("sin(a) =", np.sin(a))

# Matrix Multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("\nnp.dot(A, B):")
print(np.dot(A, B))

print("\nA @ B:")
print(A @ B)

# Aggregation Functions
arr = np.array([1, 2, 3, 4])

print("\nSum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())
print("Standard Deviation:", arr.std())


a + b = [5 7 9]
a * b = [ 4 10 18]
sin(a) = [0.84147098 0.90929743 0.14112001]

np.dot(A, B):
[[19 22]
 [43 50]]

A @ B:
[[19 22]
 [43 50]]

Sum: 10
Mean: 2.5
Max: 4
Min: 1
Standard Deviation: 1.118033988749895
